description "Bitcoin Cash II Daemon"

start on runlevel [2345]
stop on starting rc RUNLEVEL=[016]

env BITCOINCASHIID_BIN="/usr/bin/bitcoincashIId"
env BITCOINCASHIID_USER="bitcoincashII"
env BITCOINCASHIID_GROUP="bitcoincashII"
env BITCOINCASHIID_PIDDIR="/var/run/bitcoincashIId"
# upstart can't handle variables constructed with other variables
env BITCOINCASHIID_PIDFILE="/var/run/bitcoincashIId/bitcoincashIId.pid"
env BITCOINCASHIID_CONFIGFILE="/etc/bitcoincashII/bitcoin.conf"
env BITCOINCASHIID_DATADIR="/var/lib/bitcoincashIId"

expect fork

respawn
respawn limit 5 120
kill timeout 600

pre-start script
    # this will catch non-existent config files
    # bitcoincashIId will check and exit with this very warning, but it can do so
    # long after forking, leaving upstart to think everything started fine.
    # since this is a commonly encountered case on install, just check and
    # warn here.
    if ! grep -qs '^rpcpassword=' "$BITCOINCASHIID_CONFIGFILE" ; then
        echo "ERROR: You must set a secure rpcpassword to run bitcoincashIId."
        echo "The setting must appear in $BITCOINCASHIID_CONFIGFILE"
        echo
        echo "This password is security critical to securing wallets "
        echo "and must not be the same as the rpcuser setting."
        echo "You can generate a suitable random password using the following "
        echo "command from the shell:"
        echo
        echo "bash -c 'tr -dc a-zA-Z0-9 < /dev/urandom | head -c32 && echo'"
        echo
        echo "It is recommended that you also set alertnotify so you are "
        echo "notified of problems:"
        echo
        echo "ie: alertnotify=echo %%s | mail -s \"Bitcoin Cash II Alert\"" \
            "admin@foo.com"
        echo
        exit 1
    fi

    mkdir -p "$BITCOINCASHIID_PIDDIR"
    chmod 0755 "$BITCOINCASHIID_PIDDIR"
    chown $BITCOINCASHIID_USER:$BITCOINCASHIID_GROUP "$BITCOINCASHIID_PIDDIR"
    chown $BITCOINCASHIID_USER:$BITCOINCASHIID_GROUP "$BITCOINCASHIID_CONFIGFILE"
    chmod 0660 "$BITCOINCASHIID_CONFIGFILE"
end script

exec start-stop-daemon \
    --start \
    --pidfile "$BITCOINCASHIID_PIDFILE" \
    --chuid $BITCOINCASHIID_USER:$BITCOINCASHIID_GROUP \
    --exec "$BITCOINCASHIID_BIN" \
    -- \
    -pid="$BITCOINCASHIID_PIDFILE" \
    -conf="$BITCOINCASHIID_CONFIGFILE" \
    -datadir="$BITCOINCASHIID_DATADIR" \
    -disablewallet \
    -daemon
